### ISSUE TITLE
dump dex报错

### ISSUE THREAD

**Issue by CreditTone** [lasting-yang/frida_dump#2]
-> [find dex]: /data/data/<pre-initialized>/files/ac996630_3f648.dex
Error: failed to open file (No such file or directory)
    at /dump_dex.js:62

**Comment by lasting-yang** [comment]
你的app启动时，还没有files目录，可以改改脚本，写到其他目录

**Comment by CreditTone** [comment]
大哥你优化下吧，我脱壳是渣渣。牛逼的人都是自己精通一两门技术其他只要找各方面专家合作就行。我爬虫牛逼，你脱壳牛逼。以后相互学习哈。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lasting-yang <notifications@github.com&gt;
发送时间: 2020年5月14日 11:06
收件人: lasting-yang/frida_dump <frida_dump@noreply.github.com&gt;
抄送: guozhong <1273568669@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[lasting-yang/frida_dump] dump dex报错 (#2)





 
你的app启动时，还没有files目录，可以改改脚本，写到其他目录
